name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Prepare NodeJS environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '18.18.2'
    - name: Install dependencies
      run: npm install
    - name: Build application
      run: npm run build
    - name: Install SSH key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Pull changes on server
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p 65002 "source ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && npm i && rm -rf /dist && rm -rf /.cache && exit"
    - name: Cleanup SSH key
      run: rm -rf ~/.ssh
    - name: Push files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.pintucokelat.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        server-dir: /public_html/cms.pintucokelat.com/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/config/**
          **/database/**
          **/public/**
          **/src/**
          **/types/**
          package.json
          package-lock.json
          
