name: Build and Deploy
on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Pull changes on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "pintucokelat.com"
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 65002
          command_timeout: 30m
          debug: true
          script: |
            "source ${{secrets.WORK_DIR}}"
            "node -v
